#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
#  Ledger — first-time .env generator
#  Generates all secrets, prompts for the few values only you can know,
#  writes .env with secure perms (600).
#
#  Usage:  ./bootstrap.sh
#  Re-run: delete .env first, then re-run (we refuse to overwrite).
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  echo "❌ $ENV_FILE already exists."
  echo "   Refusing to overwrite — back it up (especially ENCRYPTION_KEY!) then delete it."
  exit 1
fi

command -v openssl >/dev/null || { echo "openssl not installed"; exit 1; }

echo "→ Generating cryptographically random secrets..."
DB_ROOT_PASSWORD=$(openssl rand -base64 32 | tr -d '\n=+/')
DB_PASSWORD=$(openssl rand -base64 32     | tr -d '\n=+/')
JWT_SECRET=$(openssl rand -hex 64)
ENCRYPTION_KEY=$(openssl rand -hex 32)   # 32 bytes = 64 hex chars

echo
echo "→ Need a few values you must provide:"
read -rp "  Domain (e.g. ledger.example.com — without https://): " DOMAIN
read -rp "  Your Gmail address (only this email will be allowed in): " ALLOWED_EMAIL
read -rp "  Google OAuth Client ID (xxxxx.apps.googleusercontent.com): " GOOGLE_CLIENT_ID
read -rp "  Plaid Client ID: " PLAID_CLIENT_ID
read -rsp "  Plaid Production Secret (input hidden): " PLAID_SECRET
echo
echo

if [[ -z "$DOMAIN" ]]; then
  echo "❌ Domain is required."
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# ─────────────────────────────────────────────────────────────────────
# Generated by bootstrap.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# DO NOT COMMIT THIS FILE TO GIT.
# ─────────────────────────────────────────────────────────────────────
NODE_ENV=production

# ─── Domain ──────────────────────────────────────────────────────
APP_URL=https://${DOMAIN}
CORS_ORIGIN=https://${DOMAIN}

# ─── Database ────────────────────────────────────────────────────
DB_NAME=ledger
DB_USER=ledger
DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
DB_PASSWORD=${DB_PASSWORD}

# ─── Auth secrets ────────────────────────────────────────────────
# ⚠  ENCRYPTION_KEY: if lost, ALL encrypted data is unrecoverable
#    (Plaid access tokens, encrypted note content).
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ─── Google SSO ──────────────────────────────────────────────────
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ALLOWED_EMAILS=${ALLOWED_EMAIL}

# ─── Plaid ───────────────────────────────────────────────────────
PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
PLAID_SECRET=${PLAID_SECRET}
PLAID_ENV=production
PLAID_REDIRECT_URI=https://${DOMAIN}/
PLAID_WEBHOOK_URL=https://${DOMAIN}/api/plaid/webhook

# ─── Misc ────────────────────────────────────────────────────────
SIGNUP_MODE=closed

# ─── Email subsystem ──────────────────────────────────────────────
# disabled = no emails sent (default). Set to "enabled" once you've
# configured + tested the SMTP creds below. UI greys out Email Notifs
# whenever this is disabled.
EMAIL_CONFIG=disabled

# SMTP (only used when EMAIL_CONFIG=enabled; leave SMTP_HOST blank for dev logs)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=Ledger <noreply@${DOMAIN}>
EOF

chmod 600 "$ENV_FILE"

echo "✓ $(pwd)/$ENV_FILE created (chmod 600)"
echo
echo "═══════════════════════════════════════════════════════════════════"
echo "  ⚠  BACK UP YOUR ENCRYPTION_KEY NOW:"
echo
echo "     ${ENCRYPTION_KEY}"
echo
echo "  Save this in a password manager. If you lose it, all Plaid"
echo "  access tokens and encrypted note content become unrecoverable."
echo "═══════════════════════════════════════════════════════════════════"
echo
echo "Next steps:"
echo "  1. docker compose build"
echo "  2. docker compose up -d"
echo "  3. docker compose exec backend npm run migrate"
echo "  4. Open https://${DOMAIN} and sign in with Google"
