# SPDX-License-Identifier: AGPL-3.0-or-later
FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache python3 make g++ && ln -sf python3 /usr/bin/python
COPY package*.json ./
RUN npm install --omit=dev
COPY src ./src
EXPOSE 4000
CMD ["node", "src/server.js"]